services:
  jira-xray-cloud-mcp:
    container_name: jira-xray-cloud-mcp
    image: jira-xray-cloud-mcp:latest
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: production
    env_file:
      - .env
    environment:
      FASTMCP_TRANSPORT: http
      FASTMCP_HOST: 0.0.0.0
      FASTMCP_PORT: "8000"
    #ports:
    #  - "8000:8000"
    restart: unless-stopped
